name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # We tell npm exactly WHICH folder to look in
      - name: Install Dependencies
        run: npm install
        working-directory: ./my-react-app

      # We tell Vite exactly WHICH folder to build
      - name: Build React App
        run: npm run build
        working-directory: ./my-react-app

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # Look for the 'dist' folder INSIDE 'my-react-app'
          source: "my-react-app/dist/*"
          target: "/var/www/html/"
          # 2 components = strip 'my-react-app' and 'dist'
          strip_components: 2